import numpy as np
import pandas as pd
subgenres_to_genres = {
    "deep tech house": "house",
    "deep progressive house": "house",
    "dark progressive house": "house",
    "funky tech house": "house",
    "deep deep tech house": "house",
    "tech house": "house",
    "deep deep house": "house",
    "jackin’ house": "house",
    "funky house": "house",
    "organic house": "house",
    "minimal tech house": "house",
    "classic house": "house",
    "tribal house": "house",
    "deep euro house": "house",
    "soulful house": "house",
    "deep house": "house",
    "bouncy house": "house",
    "deep groove house": "house",
    "diva house": "house",
    "bass house": "house",
    "fidget house": "house",
    "float house": "house",
    "classic progressive house": "house",
    "progressive house": "house",
    "slap house": "house",
    "deep tropical house": "house",
    "tropical house": "house",
    "stutter house": "house",
    "future house": "house",
    "minimal dubstep": "dubstep",
    "deep dubstep": "dubstep",
    "deep filthstep": "dubstep",
    "classic dubstep": "dubstep",
    "filthstep": "dubstep",
    "gaming dubstep": "dubstep",
    "deathstep": "dubstep",
    "riddim dubstep": "dubstep",
    "tearout": "dubstep",
    "brostep": "dubstep",
    "goa trance": "trance",
    "goa psytrance": "trance",
    "progressive psytrance": "trance",
    "psychedelic trance": "trance",
    "dark psytrance": "trance",
    "tech trance": "trance",
    "cosmic uplifting trance": "trance",
    "bubble trance": "trance",
    "deep psytrance": "trance",
    "deep progressive trance": "trance",
    "progressive uplifting trance": "trance",
    "deep uplifting trance": "trance",
    "acid trance": "trance",
    "progressive trance": "trance",
    "old school hard trance": "trance",
    "forest psy": "trance",
    "deep full on": "trance",
    "full on": "trance",
    "deep minimal techno": "techno",
    "dark techno": "techno",
    "raw techno": "techno",
    "dark minimal techno": "techno",
    "deep techno": "techno",
    "minimal techno": "techno",
    "acid techno": "techno",
    "industrial techno": "techno",
    "modular techno": "techno",
    "bleep techno": "techno",
    "deep liquid bass": "drum and bass",
    "jump up": "drum and bass",
    "neuro step": "drum and bass",
    "darkstep": "drum and bass",
    "neurofunk": "drum and bass"
}

df = pd.read_csv("tracks.csv")

df['Main Genre'] = df['Genre'].map(subgenres_to_genres)

df.to_csv("tracks.csv", index=False)

